spaces:
- identifier: space://myspace
  endpoints:
  - name: greeter
    type: accessor
    grammar:
      base: res://hello
    cmd: ./bin/greeter

  - name: namer
    type: accessor
    cmd: ./bin/namer
    grammar:
      base: res://name/
      groups:
        - name: nameArg
          regex: ".*"

  - name: testfile
    type: accessor
    cmd: ./bin/fileset
    grammar:
      base: res://file/
      groups:
        - name: path
          regex: ".*"
