spaces:
- identifier: space://myspace
  endpoints:
  - name: greeter
    grammar:
      base: res://hello
    cmd: ./bin/greeter

  - name: namer
    cmd: ./bin/namer
    grammar:
      base: res://name/
      groups:
        - name: nameArg
          regex: ".*"
